# 기본 환경 선택
spring:
  profiles:
    active: local 

# local 환경
---
spring:
  profiles: local
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_test?autoreconnect=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 6000
eureka:
  instance:
    preferIpAddress: true 

# 개발 환경
---
spring:
  profiles: dev
  application:
    name: auth-service
server:
  port: 6000
eureka:
  instance:
    preferIpAddress: true 

# 운영 환경
---
spring:
  profiles: ops
  application:
    name: auth-service
server:
  port: 6000 
eureka:
  instance:
    preferIpAddress: true 