# 기본 환경 선택
spring:
  profiles:
    active: local 

# local 환경
---
spring:
  profiles: local
  application:
    name: auth-service
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: root
      password: 1234
  h2:
    console:
      enabled: true
server:
  port: 6050
eureka:
  instance:
    preferIpAddress: true 

# 개발 환경
---
spring:
  profiles: dev
  application:
    name: auth-service
server:
  port: 6050
eureka:
  instance:
    preferIpAddress: true 

# 운영 환경
---
spring:
  profiles: ops
  application:
    name: auth-service
server:
  port: 6050 
eureka:
  instance:
    preferIpAddress: true 