# 기본 환경 선택
spring:
  profiles:
    active: local 

# local 환경
---
spring:
  profiles: local
  application:
    name: user-service
server:
  port: 6010
eureka:
  instance:
    preferIpAddress: true 

# 개발 환경
---
spring:
  profiles: dev
  application:
    name: user-service
server:
  port: 6767
eureka:
  instance:
    preferIpAddress: true 

# 운영 환경
---
spring:
  profiles: ops
  application:
    name: user-service
server:
  port: 6767 
eureka:
  instance:
    preferIpAddress: true 