# 기본 환경 선택
spring:
  profiles:
    active: local 

# local 환경
---
spring:
  profiles: local
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true 
  client:
    healthcheck:
      enabled: true

# 개발 환경
---
spring:
  profiles: dev
  application:
    name: discovery
server:
  port: 8761
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true 
  client:
    healthcheck:
      enabled: true

# 운영 환경
---
spring:
  profiles: ops
  application:
    name: discovery
server:
  port: 8761 
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
    preferIpAddress: true 
  client:
    healthcheck:
      enabled: true